-- DO NOT REMOVE UNDER
ALTER USER SA SET LOCAL TRUE;
-- DO NOT REMOVE OVER

-- RULES:
--    VARCHAR2 -> VARCHAR



-- CHANGE DATABASE STRUCTURE
CREATE TABLE "USERS"
(	"ID" INTEGER NOT NULL PRIMARY KEY,
   "FIRST_NAME" VARCHAR(100),
   "LAST_NAME" VARCHAR(100),
   "AGE" INTEGER
) ;

-- CHANGE DATABASE CONTENT
Insert into USERS (ID, FIRST_NAME, LAST_NAME, AGE) values (0, 'Lars Kristian', 'Johansen', 25);